### ISSUE TITLE
ChildViewController ViewWillAppear and DidAppear is not getting called!!!!

### ISSUE THREAD

**Issue by gmansata6290** [PageMenu/PageMenu#192]
How to customise the width of the childViewController ?

**Comment by Mkey85** [comment]
Same here

**Comment by Mkey85** [comment]
Ok here is the solution (worked for me):
https://github.com/HighBay/PageMenu/issues/133

**Comment by daffodilistic** [comment]
Hi all,

I managed to get the viewDidAppear() method to fire by changing code in the parent view (i.e. the view controller that the CAPSPageMenu is being added):

Original example code (not working):
```swift
// Lastly add page menu as subview of base view controller view
// or use pageMenu controller in you view hierachy as desired
self.view.addSubview(pageMenu!.view)
```
Working code:
```swift
// Lastly add page menu as subview of base view controller view
// or use pageMenu controller in you view hierachy as desired
self.addChildViewController(pageMenu!)
self.view.addSubview(pageMenu!.view)
pageMenu!.didMoveToParentViewController(self)
```

**Comment by gmansata6290** [comment]
@daffodilistic thanks man it works for me.

**Comment by dilipiOSDeveloper** [comment]
thanks it worked for me
