### ISSUE TITLE
White spaces in between controller on swipe

### ISSUE THREAD

**Issue by Albinzr** [PageMenu/PageMenu#316]
When I'm swiping very fast I'm able to see whitespace(blank white space), which is looking very bad

**Comment by nonesc** [comment]
+1

**Comment by andriofrizon** [comment]
+1

**Comment by andriofrizon** [comment]
I'm having the same problem, when changing pages slowly everything works fine, but when swiping fast a whitespace starts flickering, here's a gif of the flickering:

![caps_page_menu_flickering](https://user-images.githubusercontent.com/23064049/29328364-ad932a98-81c8-11e7-8311-e4b2ba516c2c.gif)

**Comment by joshwolff1** [comment]
Set the background to a different color

pageMenu!.view.backgroundColor = // not white

**Comment by Albinzr** [comment]
@joshwolff1 that is more of a hack than a fix

**Comment by joshwolff1** [comment]
How is that a hack?

The "fix" would be to update the repo and include a property in the enum CAPSPageMenuOption, which would do the exact same thing but be more accessible.

But arguably you're adding a view to your controller, and setting the background color of the view, which is a very straightforward and common thing to do.

**Comment by joshwolff1** [comment]
Furthermore, thought I'd add, it's a fix because the literal issue is that the backgroundColor of the pageMenu is white. And then you have your custom view controllers that you swipe between. That's why white is showing - it's simply the view of the pageMenu. The fix is to make it not white.

**Comment by Albinzr** [comment]
ok I understand
