### ISSUE TITLE
Bug? :: First controller is bigger than screen

### ISSUE THREAD

**Issue by AndresCianio** [PageMenu/PageMenu#347]
I'm using this awesome component to display two tables, but the same happens with scrollviews (and I think any view for that matter).

The thing is that the controller that appears first has its lower border out of the screen, it seems it is not properly calculating the height because the space that is out of the bounds is the same height as the menu bar.
Weird thing is that when I change to the other controller this one appears perfect. Even more, when I go back to the first one, it is fixed!

It's like there's some calculation done on refresh but it doesn't happen the first time the controller is loaded.

Any ideas?

**Comment by cjdodiya** [comment]
Getting the same issue. I've added 3 controllers. When the first one presented for the first time, view didn't loaded properly. Some portion at the bottom was missing. After moving to second page, it all work out properly. After that coming back to the first also worked properly. Please provide the solution.

**Comment by sam1411** [comment]
In the setUpUserInterface function, change this line: 
"controllerScrollView.frame = CGRect(x: 0.0, y: configuration.menuHeight, width: self.view.frame.width, height: self.view.frame.height - configuration.menuHeight)"

to :

"controllerScrollView.frame = CGRect(x: 0.0, y: configuration.menuHeight, width: self.view.frame.width, height: self.view.frame.height)"

**Comment by AndresCianio** [comment]
Proposed fix in PR #364

**Comment by AndresCianio** [comment]
PR Merged. Closing Issue.
