### ISSUE TITLE
First Tab Not Scrolling till end.

### ISSUE THREAD

**Issue by KhushalDugar** [PageMenu/PageMenu#377]
I am being using this repo in many of my project its very nice and developer friendly but now i am facing some problem i.e., I am adding 3-4 tabs but the first tab does not scroll till end but when we move to any other tab and come back first tab scrolls till end and all other tabs work fine. Does anyone have the same issue i am having?

If possible please also add option for making custom frame PageMenu.

Thanks in advance

**Comment by chandansingh5** [comment]
@KhushalDugar  Please check Answer  https://github.com/PageMenu/PageMenu/issues/355

**Comment by KhushalDugar** [comment]
Thanks @chandansingh5
