### ISSUE TITLE
project not running  dyld: Library not loaded:

### ISSUE THREAD

**Issue by skander300** [PageMenu/PageMenu#402]
dyld: Library not loaded: @rpath/PageMenu.framework/PageMenu
  Referenced from: /var/containers/Bundle/Application/993B5698-76EE-4FC4-8A46-5851DB977F3A/PageMenuDemoStoryboard.app/PageMenuDemoStoryboard
  Reason: image not found

any solution ?

**Comment by ykws** [comment]
@skander300 Hi, how did you resolve? I have a same issue.

**Comment by skander300** [comment]
i don't remember exactly but i think i solved it by re-installing the pod

**Comment by ykws** [comment]
@skander300 Thank you for reply!
This demo projects don't have a Podfile, you added it and `pod install`?
